AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  lambdabackup:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::538716083554:role/lambda_post'
      VpcConfig:
        SecurityGroupIds:
          - sg-03de9e63ba51040ac
        SubnetIds:
          - subnet-0aa5ce9926cb44d2b
          - subnet-0527a568ed56ba08c
          - subnet-0b38515aee5509179
          - subnet-0a391ef82a379f201
          - subnet-0aaa2bbb6993b5ad1
          - subnet-078c0e07280fadc24
      Environment:
        Variables:
          mysql_db: dev
          mysql_host: globant-db.cj87vungcxjk.us-east-1.rds.amazonaws.com
          mysql_pw: globantadmin
          mysql_user: admin
      Layers:
        - 'arn:aws:lambda:us-east-1:538716083554:layer:fastavro:1'
        - 'arn:aws:lambda:us-east-1:538716083554:layer:awswrangler:1'
        - 'arn:aws:lambda:us-east-1:538716083554:layer:pymsql:1'
